[package]
name = "galactica-vmd"
version = "0.1.0"
edition = "2021"
authors = ["Kirby"]
license = "GPL-3.0"
description = "VM manager daemon for Galactica OS"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1"
thiserror = "1"
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
tempfile = "3"