[package]
name = "gallium"
version = "0.1.0"
edition = "2021"
authors = ["Kirby"]
license = "GPL-3.0"
description = "Wayland compositor for Galactica OS"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
smithay = "0.3"          # Wayland compositor framework
calloop = "0.11"         # Event loop (used by Smithay)
glow = "0.13"            # OpenGL bindings for Rust
glium = "0.36.0"
