[package]
name = "galactica-compositor"
version = "0.1.0"
edition = "2021"
authors = ["Kirby"]
license = "GPL-3.0"
description = "Wayland compositor for Galactica OS"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]