[book]
title = "Galactica OS Documentation"
authors = ["Galactica Team"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/yourusername/galactica-os"